apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hellok8s
  namespace: default
spec:
  components:
    - name: hellok8s
      type: webservice
      annotations:
        reloader.stakater.com/auto: "true"
      properties:
        image: busybox
        ports:
          - port: 80
        cmd:
          - sleep
          - "3600"
      traits:
        - type: envfrom
          properties:
            configMaps:
              - name: "test-cm"
                data:
                  MY_KEY: "MY_VALUE_2"
